Avance de 18/04/23
KevinMed25/CursoWeb pull request #4
Opened 2023-04-19 07:50 UTC by KevinMed25

Añadí un poco de código y elimine el .DS_Store que menciono Marcelo

2023-04-19 23:51 UTC, CheloChidoone requested changes, later dismissed
@KevinMed25, Vimos que terminaste ya la sección 7 pero tu proyecto esta incompleto, en la Pagina de "Nosotros" no cargan las imágenes que pusiste porque pusiste mal el src en tus etiquetas img, y la pagina de "Producto" no la completaste, complétalo por favor, si tienes dudas de lo que te digo pregúntanos por tu canal de status en discord y ahí podemos platicarlo

2023-04-20 03:21 UTC, jfer1990 approved these changes

2023-04-20 03:21 UTC, jfer1990 approved these changes, later dismissed

2023-04-20 03:33 UTC, jfer1990 requested changes
Corrige porfa los enlaces rotos en la página de nosotros, y veo que te hace falta realizar la página de producto

2023-04-20 04:49 UTC, closed without merging